name: Weekly Waiver Wire Alert

on:
  schedule:
    - cron: '0 12 * * 2'
  workflow_dispatch:

jobs:
  send-alert:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip install requests
        
    - name: Run waiver wire script
      env:
        GROK_API_KEY: ${{ secrets.GROK_API_KEY }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: python waiver_wire.py